# Generated by Django 4.2.6 on 2023-11-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
